name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: 

permissions:
  contents: write

env: 
  EXEC: SDL_gpu_examples
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      tag: ${{ steps.time-tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Extract version from tag 
#        id: version 
#        run: | 
#          VERSION="${GITHUB_REF#refs/tags/}" 
#          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate timestamp tag 
        id: time-tag 
        run: | 
          TAG="release-$(date +'%Y%m%d-%H%M%S')" 
          echo "Generated tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config cmake ninja-build git

      - name: Build and install SDL3 from source 
        run: |
          sudo apt-get install -y gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev
          git clone https://github.com/libsdl-org/SDL.git 
          cd SDL 
          mkdir build
          cd build
          cmake ..
          make
       
      - name: Build Examples
        run: |
          mkdir build
          cd build
          cmake .. -DSDL3_DIR="../SDL/build"

      - name: Make project
        run: |
          cd build
          make

      - name: Archive executable
        run: |
          pwd
          cd build
          mkdir -p dist
          ls -hsl .
          file ${EXEC}
          cp ${EXEC} dist/${EXEC}

      - name: Upload build artifacts 
        uses: actions/upload-artifact@v4 
        with: 
          name: artifact 
          path: build/dist/
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4 
      - name: Download build artifacts 
        uses: actions/download-artifact@v4 
        with: 
          name: artifact 
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: ${{ needs.build.outputs.tag }}
          name: ${{ env.EXEC }}
          files: dist/${{ env.EXEC }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
